version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: node_keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet
  pgadmin:
    image: dpage/pgadmin4
    logging:
      driver: none
    restart: always
    networks:
      - webnet
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@megadodo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - 3051:80
    volumes:
      - pgadmin:/var/lib/pgadmin
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3050:80
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: node_keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_FRONTEND_URL: "http://localhost:3050/auth"
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      - webnet
    ports:
      - 8080:8080
    depends_on:
      - postgres
networks:
  webnet:
volumes:
  pgdata:
    driver: local
  pgadmin:
    driver: local
